logging:
  level: INFO
  loggers:
    com.github.phillbarber: DEBUG
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: target/keys/server/5-keystore-with-privatekey-and-publiccert.p12
      keyStorePassword: abcdefg
      keyStoreType: PKCS12